export default function getAllProducts() {
  return [
    // Produk kategori Peralatan Memasak
    {
      id: 'CU-001',
      slug: 'spatula-001',
      name: 'Spatula Silikon',
      category: 'Peralatan Memasak',
      categorySlug: 'peralatan-memasak',
      price: 50000,
      stock: 100,
      imageUrl: 'https://i5.walmartimages.com/asr/29522ebc-a3e7-4ecf-8e58-7981d75231d9_1.9ef07842a82c97ca40bbc1c9c5123e10.jpeg',
      description: 'Spatula silikon yang fleksibel dan tahan panas.',
    },
    {
      id: 'CU-002',
      slug: 'panci-001',
      name: 'Panci Stainless Steel',
      category: 'Peralatan Memasak',
      categorySlug: 'peralatan-memasak',
      price: 250000,
      stock: 20,
      imageUrl: 'https://ceklist.id/wp-content/uploads/2022/05/Merk-Panci-Terbaik-1024x719.jpg',
      description: 'Panci stainless steel dengan lapisan anti lengket.',
    },
    {
      id: 'CU-003',
      slug: 'pengocok-001',
      name: 'Pengocok Telur',
      category: 'Peralatan Memasak',
      categorySlug: 'peralatan-memasak',
      price: 30000,
      stock: 50,
      imageUrl: 'https://cf.shopee.co.id/file/9bb613dbf2b1bb70d46ace7db0c682e0',
      description: 'Pengocok telur yang ergonomis dan mudah digunakan.',
    },
    {
      id: 'CU-004',
      slug: 'sendok-001',
      name: 'Sendok Kayu',
      category: 'Peralatan Memasak',
      categorySlug: 'peralatan-memasak',
      price: 15000,
      stock: 150,
      imageUrl: 'https://asset-a.grid.id/crop/0x0:0x0/750x504/photo/2020/10/04/4285881835.jpg',
      description: 'Sendok kayu yang ramah lingkungan dan tidak merusak panci.',
    },
    {
      id: 'CU-005',
      slug: 'serut-001',
      name: 'Serut Sayur',
      category: 'Peralatan Memasak',
      categorySlug: 'peralatan-memasak',
      price: 20000,
      stock: 80,
      imageUrl: 'https://down-id.img.susercontent.com/file/e417201f1d61500c4a09e63d465fdf3chttps://cf.shopee.co.id/file/d70d775d43f49b970df899a9f34f4867',
      description: 'Serut sayur stainless steel yang tajam dan tahan lama.',
    },
    
    // Produk kategori Peralatan Penyajian
    {
      id: 'CU-006',
      slug: 'piring-001',
      name: 'Piring Keramik',
      category: 'Peralatan Penyajian',
      categorySlug: 'peralatan-penyajian',
      price: 30000,
      stock: 50,
      imageUrl: 'https://gratisongkir-storage.com/products/900x900/imQTTCW1mDsK.jpg',
      description: 'Piring keramik yang elegan untuk menyajikan hidangan.',
    },
    {
      id: 'CU-007',
      slug: 'gelas-001',
      name: 'Gelas Kaca',
      category: 'Peralatan Penyajian',
      categorySlug: 'peralatan-penyajian',
      price: 15000,
      stock: 100,
      imageUrl: 'https://th.bing.com/th/id/OIP.Kq9cOGTu19uxQpWDHqtU-wHaHa?rs=1&pid=ImgDetMain',
      description: 'Gelas kaca yang cocok untuk berbagai minuman.',
    },
    {
      id: 'CU-008',
      slug: 'sendok-saji-001',
      name: 'Sendok Saji',
      category: 'Peralatan Penyajian',
      categorySlug: 'peralatan-penyajian',
      price: 20000,
      stock: 75,
      imageUrl: 'https://res.cloudinary.com/ruparupa-com/image/upload/h_1000,w_1000,f_auto/f_auto,q_auto:eco/v1696518573/Products/10540069_1.jpg',
      description: 'Sendok saji yang praktis untuk menyajikan makanan.',
    },
  ];
}
